FROM node:20-alpine

WORKDIR /opt/e-commerce/services/product-service

RUN npm install -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npx", "nodemon", "--watch", ".", "src/app.js"]