FROM node:20-alpine AS build

WORKDIR /opt/e-commerce/frontend

RUN addgroup -S app && adduser -S app -G app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

RUN chown -R app:app /opt/e-commerce
USER app

FROM nginx:alpine AS prod

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /opt/e-commerce/frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]