FROM node:20-alpine

WORKDIR /opt/e-commerce/services/order-service

RUN addgroup -S app && adduser -S app -G app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

RUN chown -R app:app /opt/e-commerce
USER app

EXPOSE 3002

CMD ["npm", "start"]